# coding: utf-8

import json
import os

# Path to the UAT.json file generated by UAT_transform.py
uat_flat = 'UAT.json'

def load_uat_data(file_path):
    """Load UAT data from a JSON file."""
    with open(file_path, 'r', encoding='utf-8') as file:
        return json.load(file)

def save_term_to_file(term, directory='.', file_extension='.json'):
    """Save a term to a JSON file."""
    name = term.get('name')
    if name:
        filename = name.lower().replace(" ", "_").replace("(", "").replace(")", "") + file_extension
        file_path = os.path.join(directory, filename)
        with open(file_path, 'w', encoding='utf-8') as file:
            json.dump(term, file, ensure_ascii=False, indent=4)

def main():
    data = load_uat_data(uat_flat)
    child_terms = data.get('children', [])

    for term in child_terms:
        save_term_to_file(term)

if __name__ == '__main__':
    main()